# Generated by Django 5.2.6 on 2025-09-16 00:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('stored_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.conversation')),
            ],
            options={
                'indexes': [models.Index(fields=['conversation', 'filename'], name='app_fileart_convers_9ed9bc_idx'), models.Index(fields=['conversation', 'path'], name='app_fileart_convers_35a40d_idx')],
            },
        ),
    ]
