# Generated by Django 4.2.24 on 2025-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='daytona_volume_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='daytona_volume_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
