# Generated by Django 4.2.24 on 2025-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_fileartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agent_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='llm_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
